In [9]:
import pandas as pd
import numpy as np

# Task 1
data = np.random.rand(4, 4)

In [10]:
data

array([[0.19764982, 0.85974154, 0.20988391, 0.55318972],
       [0.69178221, 0.84980339, 0.57389628, 0.30480655],
       [0.96682866, 0.70111379, 0.04266419, 0.59455912],
       [0.17190737, 0.73209002, 0.75312318, 0.82724163]])

In [11]:
df = pd.DataFrame(data, columns=[' 1', ' 2', ' 3', ' 4'])

df

          1         2         3         4
0  0.197650  0.859742  0.209884  0.553190
1  0.691782  0.849803  0.573896  0.304807
2  0.966829  0.701114  0.042664  0.594559
3  0.171907  0.732090  0.753123  0.827242

In [12]:

# Task 2
df.rename(columns={' 1': 'Random value 1',
                   ' 2': 'Random value 2',
                   ' 3': 'Random value 3',
                   ' 4': 'Random value 4'}, inplace=True)

df

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.197650        0.859742        0.209884        0.553190
1        0.691782        0.849803        0.573896        0.304807
2        0.966829        0.701114        0.042664        0.594559
3        0.171907        0.732090        0.753123        0.827242

In [13]:
# Task 3
descriptive_stats = df.describe()
descriptive_stats

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.507042        0.785687        0.394892        0.569949
std          0.388832        0.080871        0.325916        0.213999
min          0.171907        0.701114        0.042664        0.304807
25%          0.191214        0.724346        0.168079        0.491094
50%          0.444716        0.790947        0.391890        0.573874
75%          0.760544        0.852288        0.618703        0.652730
max          0.966829        0.859742        0.753123        0.827242

In [14]:
# Task 4
null_values = df.isnull().sum()
data_types = df.dtypes

null_values

Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64

In [15]:
data_types

Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object

In [17]:
# Task 5
random_value_2_loc = df.loc[:, 'Random value 2']
random_value_3_loc = df.loc[:, 'Random value 3']

random_value_2_idx = df.iloc[:, 1]
random_value_3_idx = df.iloc[:, 2]

# Display results
print("Task 1: DataFrame 'df'")
print(df)

print("\nTask 2: DataFrame after column renaming")
print(df)

print("\nTask 3: Descriptive Statistics")
print(descriptive_stats)

print("\nTask 4: Null Values and Data Types")
print("Null Values:")
print(null_values)
print("\nData Types:")
print(data_types)

print("\nTask 5: Random value 2 and Random value 3 columns")
print("Using .loc:")
print(random_value_2_loc)
print(random_value_3_loc)
print("\nUsing iloc:")
print(random_value_2_idx)
print(random_value_3_idx)

Task 1: DataFrame 'df'
   Random value 1  Random value 2  Random value 3  Random value 4
0        0.197650        0.859742        0.209884        0.553190
1        0.691782        0.849803        0.573896        0.304807
2        0.966829        0.701114        0.042664        0.594559
3        0.171907        0.732090        0.753123        0.827242

Task 2: DataFrame after column renaming
   Random value 1  Random value 2  Random value 3  Random value 4
0        0.197650        0.859742        0.209884        0.553190
1        0.691782        0.849803        0.573896        0.304807
2        0.966829        0.701114        0.042664        0.594559
3        0.171907        0.732090        0.753123        0.827242

Task 3: Descriptive Statistics
       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.507042        0.785687        0.394892        0.569949
std          0.388832        0.080871        0.325916        0.213999
min          0.171907        0.701114        0.042664        0.304807
25%          0.191214        0.724346        0.168079        0.491094
50%          0.444716        0.790947        0.391890        0.573874
75%          0.760544        0.852288        0.618703        0.652730
max          0.966829        0.859742        0.753123        0.827242

Task 4: Null Values and Data Types
Null Values:
Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64

Data Types:
Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object

Task 5: Random value 2 and Random value 3 columns
Using .loc:
0    0.859742
1    0.849803
2    0.701114
3    0.732090
Name: Random value 2, dtype: float64
0    0.209884
1    0.573896
2    0.042664
3    0.753123
Name: Random value 3, dtype: float64

Using iloc:
0    0.859742
1    0.849803
2    0.701114
3    0.732090
Name: Random value 2, dtype: float64
0    0.209884
1    0.573896
2    0.042664
3    0.753123
Name: Random value 3, dtype: float64